experiment:
  entity: "kingvm8-k-n-toosi-university-of-technology"
  project: "Thesis-RL-Trading"
  seed: 42

hyperparameters:
  learning_rate: 0.12
  epochs: 20
  max_grad_norm: 1.0

architecture:
  input_dim: 5
  output_dim: 1